[package]
name = "cpr-reports"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
printpdf = { workspace = true }
csv = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
anyhow = { workspace = true }
cpr-core = { workspace = true }
